package fa.model;
// Generated May 20, 2016 11:09:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idklien;
     private String nama;
     private String telepon;
     private String celuler;
     private String alamat;
     private Set fakturs = new HashSet(0);

    public Client() {
    }

	
    public Client(String nama, String telepon, String celuler, String alamat) {
        this.nama = nama;
        this.telepon = telepon;
        this.celuler = celuler;
        this.alamat = alamat;
    }
    public Client(String nama, String telepon, String celuler, String alamat, Set fakturs) {
       this.nama = nama;
       this.telepon = telepon;
       this.celuler = celuler;
       this.alamat = alamat;
       this.fakturs = fakturs;
    }
   
    public Integer getIdklien() {
        return this.idklien;
    }
    
    public void setIdklien(Integer idklien) {
        this.idklien = idklien;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getTelepon() {
        return this.telepon;
    }
    
    public void setTelepon(String telepon) {
        this.telepon = telepon;
    }
    public String getCeluler() {
        return this.celuler;
    }
    
    public void setCeluler(String celuler) {
        this.celuler = celuler;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Set getFakturs() {
        return this.fakturs;
    }
    
    public void setFakturs(Set fakturs) {
        this.fakturs = fakturs;
    }




}


