package fa.model;
// Generated May 20, 2016 11:09:48 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detilfaktur generated by hbm2java
 */
public class Detilfaktur  implements java.io.Serializable {


     private Integer id;
     private Faktur faktur;
     private Produk produk;
     private String kodeproduk;
     private String namaproduk;
     private int jumlah;
     private BigDecimal hargajual;
     private BigDecimal totalharga;

    public Detilfaktur() {
    }

    public Detilfaktur(Faktur faktur, Produk produk, String kodeproduk, String namaproduk, int jumlah, BigDecimal hargajual, BigDecimal totalharga) {
       this.faktur = faktur;
       this.produk = produk;
       this.kodeproduk = kodeproduk;
       this.namaproduk = namaproduk;
       this.jumlah = jumlah;
       this.hargajual = hargajual;
       this.totalharga = totalharga;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Faktur getFaktur() {
        return this.faktur;
    }
    
    public void setFaktur(Faktur faktur) {
        this.faktur = faktur;
    }
    public Produk getProduk() {
        return this.produk;
    }
    
    public void setProduk(Produk produk) {
        this.produk = produk;
    }
    public String getKodeproduk() {
        return this.kodeproduk;
    }
    
    public void setKodeproduk(String kodeproduk) {
        this.kodeproduk = kodeproduk;
    }
    public String getNamaproduk() {
        return this.namaproduk;
    }
    
    public void setNamaproduk(String namaproduk) {
        this.namaproduk = namaproduk;
    }
    public int getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }
    public BigDecimal getHargajual() {
        return this.hargajual;
    }
    
    public void setHargajual(BigDecimal hargajual) {
        this.hargajual = hargajual;
    }
    public BigDecimal getTotalharga() {
        return this.totalharga;
    }
    
    public void setTotalharga(BigDecimal totalharga) {
        this.totalharga = totalharga;
    }




}


