package fa.model;
// Generated May 20, 2016 11:09:48 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Faktur generated by hbm2java
 */
public class Faktur  implements java.io.Serializable {


     private Integer idfaktur;
     private Client client;
     private int nofaktur;
     private BigDecimal totalharga;
     private Date register;
     private Set detilfakturs = new HashSet(0);

    public Faktur() {
    }

	
    public Faktur(Client client, int nofaktur, BigDecimal totalharga, Date register) {
        this.client = client;
        this.nofaktur = nofaktur;
        this.totalharga = totalharga;
        this.register = register;
    }
    public Faktur(Client client, int nofaktur, BigDecimal totalharga, Date register, Set detilfakturs) {
       this.client = client;
       this.nofaktur = nofaktur;
       this.totalharga = totalharga;
       this.register = register;
       this.detilfakturs = detilfakturs;
    }
   
    public Integer getIdfaktur() {
        return this.idfaktur;
    }
    
    public void setIdfaktur(Integer idfaktur) {
        this.idfaktur = idfaktur;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public int getNofaktur() {
        return this.nofaktur;
    }
    
    public void setNofaktur(int nofaktur) {
        this.nofaktur = nofaktur;
    }
    public BigDecimal getTotalharga() {
        return this.totalharga;
    }
    
    public void setTotalharga(BigDecimal totalharga) {
        this.totalharga = totalharga;
    }
    public Date getRegister() {
        return this.register;
    }
    
    public void setRegister(Date register) {
        this.register = register;
    }
    public Set getDetilfakturs() {
        return this.detilfakturs;
    }
    
    public void setDetilfakturs(Set detilfakturs) {
        this.detilfakturs = detilfakturs;
    }




}


