package fa.model;
// Generated May 20, 2016 11:09:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendor generated by hbm2java
 */
public class Vendor  implements java.io.Serializable {


     private Integer idvendor;
     private String nama;
     private String kota;
     private String celuler;
     private String alamat;
     private Set userses = new HashSet(0);

    public Vendor() {
    }

	
    public Vendor(String nama, String kota, String celuler, String alamat) {
        this.nama = nama;
        this.kota = kota;
        this.celuler = celuler;
        this.alamat = alamat;
    }
    public Vendor(String nama, String kota, String celuler, String alamat, Set userses) {
       this.nama = nama;
       this.kota = kota;
       this.celuler = celuler;
       this.alamat = alamat;
       this.userses = userses;
    }
   
    public Integer getIdvendor() {
        return this.idvendor;
    }
    
    public void setIdvendor(Integer idvendor) {
        this.idvendor = idvendor;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getKota() {
        return this.kota;
    }
    
    public void setKota(String kota) {
        this.kota = kota;
    }
    public String getCeluler() {
        return this.celuler;
    }
    
    public void setCeluler(String celuler) {
        this.celuler = celuler;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


